name: Release
on:
  release:
    types: [published]
jobs:
  attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: ./gradlew clean jar --no-daemon
      - name: Upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/thc4m3.jar
